spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue:
    consume: "associado.cart.in"
    produce: "associado.cart.out"

server:
  port: 8083
